# Generated by Django 4.0.4 on 2022-06-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=20)),
                ('stock', models.IntegerField(max_length=20)),
                ('imagen', models.CharField(default='imagen', max_length=500)),
            ],
        ),
    ]
