# Generated by Django 4.0.5 on 2022-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_mantencion',
            fields=[
                ('id_mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.EmailField(max_length=254, unique=True)),
                ('tipo_bici', models.CharField(max_length=30)),
                ('tipo_mantencio', models.CharField(max_length=30)),
                ('detalles', models.CharField(max_length=1000)),
            ],
        ),
    ]
