# Generated by Django 4.0.4 on 2022-06-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reserva_mantencion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_arriendo',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_bici', models.CharField(max_length=30)),
                ('tiempo_arriendo', models.CharField(max_length=30)),
                ('tipo_garantia', models.CharField(max_length=30)),
                ('usuario', models.EmailField(max_length=254)),
            ],
        ),
    ]
