# Generated by Django 4.0.4 on 2022-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reserva_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('subtotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('subtotal_producto', models.IntegerField()),
            ],
        ),
    ]
