# Generated by Django 4.0.4 on 2022-06-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
