# Generated by Django 4.0.4 on 2022-06-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
