# Generated by Django 4.0.5 on 2022-07-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id_promo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
