# Generated by Django 4.0.5 on 2022-07-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='codigo',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='porcentaje',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
