# Generated by Django 4.0.5 on 2022-07-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_venta_entregado'),
        ('app', '0012_alter_notificacion_fecha'),
    ]

    operations = [
    ]
